# Generated by Django 4.2.23 on 2025-08-11 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимальная длина наименования 255",
                        max_length=255,
                        verbose_name="Наименование продукта",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Слаг автоматически генерируется на основании поля name",
                        max_length=255,
                        verbose_name="Слаг продукта",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание продукта"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Стоимость продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимальная длина наименования 255",
                        max_length=255,
                        verbose_name="Наименование заказа",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Слаг автоматически генерируется на основании поля name",
                        max_length=255,
                        verbose_name="Слаг заказа",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание заказа"),
                ),
                (
                    "date_order",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Укажите дату заказа в формате DD.MM.YYYY",
                        verbose_name="Дата заказа",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_order"
            ),
        ),
    ]
