# Generated by Django 4.2.23 on 2025-08-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="api.product", verbose_name="Продукты"),
        ),
    ]
