# Generated by Django 4.2.23 on 2025-08-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_order_product_order_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="products",
        ),
    ]
