# Generated by Django 5.2.5 on 2025-08-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_fill_businesselements"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesselement",
            options={
                "verbose_name": "Бизнес-элемент",
                "verbose_name_plural": "Бизнес-элементы",
            },
        ),
    ]
