# Generated by Django 5.2.5 on 2025-08-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_alter_businesselement_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(max_length=255, verbose_name="Имя пользователя"),
        ),
        migrations.AddConstraint(
            model_name="usermodel",
            constraint=models.UniqueConstraint(
                fields=("username", "email"), name="unique_user"
            ),
        ),
    ]
